spring:
  application:
    name: dealership
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    default-schema: inventory

logging:
  level:
    com.springworkshop: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
